### ISSUE TITLE
can't run test

### ISSUE THREAD

**Issue by zxydaisy** [justinwoo/react-karma-webpack-testing#10]
$ karma start
19 12 2016 16:01:01.913:ERROR [preprocess]: Can not load "webpack", it is not registered!
  Perhaps you are missing some plugin?
19 12 2016 16:01:01.917:ERROR [preprocess]: Can not load "sourcemap", it is not registered!
  Perhaps you are missing some plugin?
/usr/local/lib/node_modules/karma/node_modules/di/lib/injector.js:9
      throw error('No provider for "' + name + '"!');
      ^

Error: No provider for "framework:mocha"! (Resolving: framework:mocha)
    at error (/usr/local/lib/node_modules/karma/node_modules/di/lib/injector.js:22:12)
    at Object.parent.get (/usr/local/lib/node_modules/karma/node_modules/di/lib/injector.js:9:13)
    at get (/usr/local/lib/node_modules/karma/node_modules/di/lib/injector.js:54:19)
    at /usr/local/lib/node_modules/karma/lib/server.js:143:20
    at Array.forEach (native)
    at Server._start (/usr/local/lib/node_modules/karma/lib/server.js:142:21)
    at invoke (/usr/local/lib/node_modules/karma/node_modules/di/lib/injector.js:75:15)
    at Server.start (/usr/local/lib/node_modules/karma/lib/server.js:103:18)
    at Object.exports.run (/usr/local/lib/node_modules/karma/lib/cli.js:280:26)
    at Object.<anonymous> (/usr/local/lib/node_modules/karma/bin/karma:3:23)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)

**Comment by MichalKononenko** [comment]
It's probably running a globally installed ``karma`` somewhere on your system. Try running ``which karma`` for Linux or ``where karma`` for Windows. Are you able to run the tests using ``npm test``?
