### ISSUE TITLE
Error on npm test

### ISSUE THREAD

**Issue by donnrri** [justinwoo/react-karma-webpack-testing#6]
Did clone -> npm install -> npm test
But I get an error 

module.js:340
    throw err;
          ^
Error: Cannot find module 'base64id'
    at Function.Module._resolveFilename (module.js:
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (c:\TestExamples\KarmaWeb
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
npm ERR! Test failed.  See above for more details.

Can you help ?

**Comment by donnrri** [comment]
OK npm allowed me eventually to install base64id, I am now getting an syntax error in karma / node modules/ socket.io/node modules/ debug/ ms /node modules /ms/ package.json ??  Long shot but any ideas ?

**Comment by donnrri** [comment]
Ok I installed ms , but now when I run npm test I'm getting more and more cannot find module errors , like isarray, parsueir, component-emitter . Can someone please tell me what I'm doing wrong here , I have run npm install ?  Thanks

**Comment by donnrri** [comment]
I cannot see where all these modules are required as dependencies , this is weird...I haven't come across this behaviour before

**Comment by MichalKononenko** [comment]
What's your node and npm versions?

**Comment by justinwoo** [comment]
Sorry, I don't use this anymore.
